services:
  webapp:
    build: .
    ports:
      - "8080:8080"
    container_name: my-tomcat-servlet
    networks:
      - b46
    depends_on:
      - postgres
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/tennisdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  postgres:
    image: postgres:15
    container_name: tennis-postgres
    restart: always
    environment:
      POSTGRES_DB: tennisdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - b46

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg-panel
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - b46
    depends_on:
      - postgres

volumes:
  pgdata:

networks:
  b46:
